version: 2.1
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
          
      - gh-actions:
          uses: actions/hello-world-docker-action@v1
          with: |
            who-to-greet: 'Mona The Octocat'

orbs:
  gh-actions: aengelberg/gh-actions@0.0.1
