version: 2.1

orbs:
  gh-actions: aengelberg/gh-actions@0.0.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date

      - gh-actions/action:
          uses: talos-systems/conform@v0.1.0-alpha.16
          with: |
            foo: 'bar'


