version: 2.1

orbs:
  gh-actions: aengelberg/gh-actions@0.0.1

jobs:
  build:
    docker:
      - image: ubuntu-1604:201903-01

    steps:
      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
          
      - gh-actions/action:
          uses: actions/hello-world-docker-action@v1
          with: |
            who-to-greet: 'Mona The Octocat'

